deployment:
  timeout: 30
  strategy:
    name: canary
    step: 10
    period: 6
    timeout: 120
    metric:
vamp:
  blueprint:
    name: codebreaker
    clusters:
      codebreaker:
        services:
        - breed:
            name: codebreaker
            deployable: codebreaker.azurecr.io/codebreaker
            ports:
              web: 80/http
            env:
              ConnectionStrings__DefaultConnection: {{{SQLSERVER_CONNECTIONSTRING}}}
          scale:
            cpu: 0.2
            memory: 64MB
            instances: 1
  gateway:
    name: codebreaker
    port: 9060/http
    routes:
      codebreaker/codebreaker/web:
        weight: 100%