apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: codebreaker
spec:
  rules:
  - host: codebreaker.lesierse.com
    http:
      paths:
      - path: /
        backend:
          serviceName: codebreaker
          servicePort: 9060