apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:stable-git
    command: ["cat"]
    tty: true
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"
  - name: vamp-cli-ee
    image: vlesierse/vamp-cli-ee:latest
    command: ["cat"]
    tty: true
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  #dnsPolicy: ClusterFirst
  #nodeSelector:
  #  kubernetes.io/role: agent
  #  beta.kubernetes.io/os: linux
  #  type: virtual-kubelet
  #tolerations:
  #- key: virtual-kubelet.io/provider
  #  operator: Exists
  #- key: azure.com/aci
  #  effect: NoSchedule

